server:
  port: 8002
spring:
  application:
    name: cloud-service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


aliyun:
  oss:
    endpoint:
    keyId: # 访问身份验证中用到用户标识
    keySecret:  # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName:
