server:
  port: 8005
spring:
  application:
    name: cloud-service-sms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 180000
    lettuce:
      pool:
        max-wait: -1
        max-idle: 5
        max-active: 20
tencent:
  sms:
    # 配置腾讯云API密钥的SecretId
    secretId:
    # 配置腾讯云API密钥的SecretKey
    secretKey:
    # 配置短信应用的SDKAppID
    appId:
    # 配置签名内容
    sign: ""
    # 配置模板ID
    templateId:
    # 配置过期时间
    expireTime: 5
    # 配置redis存储的key的前缀
    phonePrefix: REGIST